language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
    - php: hhvm-nightly
    - php: hhvm
    
services:
    - memcached

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - travis_retry composer self-update
    - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
    - travis_retry composer update
    - ./vendor/bin/codecept build -c tests
    
script:    
    - ./vendor/bin/codecept run functional -c tests
    - ./vendor/bin/codecept run unit -c tests
